### PR TITLE
chore/webpay-clean

### PR DESCRIPTION
**Pull request by DarkGhostHunter**
Was drunk yesterday and I decided to clean the Webpay SDK in one sip. Took me lot of sips, though.

* No Test was edited, deleted or added. Only the loader (which now uses composer autoload instead of the init.php) for these.
* No SOAP code was edited in anyway. This should be addressed separately.
* No changes in dependencies. This should be addressed separately.
* No changes on public-facing methods. Docs should still be valid.
* **All test passed on my end (5.5~7.0)**.

I think this should be the last version for the SDK that doesn't break the public-facing methods, until a major version arrives.

### CODE REVIEW

**Comment by DarkGhostHunter** [comment]
For some reason Semaphore CI fails to build, but on my environment all tests passes. Can I get some help? Internet died, i'm on mobile.

**Comment by DarkGhostHunter** [comment]
Please check how Somophore CI uses the docker image to run the test. I used docker on my own and all test passed.

image

**Comment by leosoto** [comment]
Awesome! Please have some patience so we can review this. There are plenty of changes (plus the weird failures on CI) so it might take a bit of time for us to come back here and give feedback. But we will do it :)

**Comment by DarkGhostHunter** [comment]
Thanks. I'll promise to get more drunk with the Onepay SDK.

**Comment by leosoto** [comment]
Haha! Let us know and we might help with the drinks 😉

**Comment by a1b4** [comment]
hello @DarkGhostHunter we really appreciate your hard work but this PR is too big for us to merge and test and we were unable to prioritize it so I will close this PR. please feel free to continue contributing but please make sure to keep changes as small as posible. keep it up 😄

**Pull request closed without merging**
